// Writes src/version.ts from package.json so the version is inlined at build
// time. Reading package.json at runtime breaks inside a compiled binary, where
// there is no package.json on disk.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf-8"));
const out = join(root, "src", "version.ts");

const contents = `// Generated by scripts/gen-version.mjs. Do not edit.\nexport const VERSION = ${JSON.stringify(version)};\n`;

let current = "";
try {
  current = readFileSync(out, "utf-8");
} catch {
  // File does not exist yet.
}

if (current !== contents) {
  writeFileSync(out, contents);
  console.log(`wrote src/version.ts (${version})`);
}
